### ISSUE TITLE
Remap CLDR translations to canonical identifiers

### ISSUE THREAD

**Issue by mj1856** [regebro/tzlocal#10]
First - thanks for this library.  Very useful, and it's certainly the correct approach.

There's one small issue though.  The CLDR mappings (from Windows to IANA) do not necessarily use canonical identifiers.  The CLDR requires stable identifiers, so when the primary name of a time zone changes, the CLDR retains the mapping to the old zone name.

There are always links in the tz data to follow, but this should probably be done as you build the `win_tz` map instead of being left to the end user.

For example, on Windows, if you set your time zone to `"India Standard Time"`, tzlocal will return `"Asia/Calcutta"` - because that's what the CLDR points to.

But `"Asia/Calcutta"` is now a link to `"Asia/Kolkata"`- which is the primary zone.  tzlocal should follow that link.

BTW - I had the same issue [with Noda Time in .NET](http://stackoverflow.com/a/17348822/634824).

**Comment by regebro** [comment]
Closing for lack of response.
