### ISSUE TITLE
Can't get timezone on windows 10

### ISSUE THREAD

**Issue by KernelErr** [regebro/tzlocal#103]
Hi, I encountered an error that tzlocal can't get local timezone. So I checked my registry and didn't find a key named 'TimeZoneKetName'. Only after I changed my timezone in the time settings manually, this key would appear. Seems that Windows wouldn't create this registry in the first run. Is it necessary to fix this problem? Thanks.

**Comment by regebro** [comment]
Strange that it didn't exist. But I don't think it's possible to fix it, except do what you did.

**Comment by synodriver** [comment]
Well,you should configure the timezone again in the control panel,then it should work. (I fixed it just now.)

**Comment by synodriver** [comment]
> Well,you should configure the timezone again in the control panel,then it should work. (I fixed it just now.)

The strange thing is that it suddenly appeared after runing for few days.
