### ISSUE TITLE
AttributeError when assigning a time zone to pandas Timestamp with no timezone

### ISSUE THREAD

**Issue by monstrorivas** [regebro/tzlocal#109]
In version tzlocal==3.0b1, I run into an AttributeError when assigning a time zone to pandas Timestamp with no timezone

It can be reproduce with the following code:
```
import pandas as pd
import datetime 
import tzlocal
pd_end = pd.to_datetime(datetime.datetime.now())
pd_end.tz_localize(tzlocal.get_localzone())
```
The same code works just fine with tzlocal==2.1 (pandas == 1.2.4 for both)

**Comment by regebro** [comment]
What is the error?

**Comment by regebro** [comment]
Oh, I see, yes, this is the API change in version 3. Version 3 uses ZoneInfo objects instead of pytz objects. If you want to use pytz, you should indeed stay with version 2.1.
