### ISSUE TITLE
`localize` is Gone in Latest Release

### ISSUE THREAD

**Issue by souch3** [regebro/tzlocal#113]
`localize` was able to be called to interpret a naive datetime as the local time zone. With the latest release, that call raises an AttributeError

```
import tzlocal
from datetime import datetime

loc = tzlocal.get_localzone()
d = datetime.now()
loc.localize(d)
```

I suspect this is due to a change in the return type to being backports.zoneinfo.ZoneInfo. I believe it used to be a pytz object? I'm assuming this is behaving correctly and we should switch our code to use `astimezone` but confirming here

**Comment by regebro** [comment]
Yes, this is correct, it now uses the Python 3 standard library timezones instead of pytz.
