### ISSUE TITLE
Possible Bug: Can not find timezone Northwest Time Border M�xico

### ISSUE THREAD

**Issue by Saijin-Naib** [regebro/tzlocal#118]
```
grass78\\Python37\\lib\\site-packages\\tzlocal\\win32.py\", line 79, in get_localzone_name
raise pytz.UnknownTimeZoneError('Can not find timezone ' + tzkeyname)
pytz.exceptions.UnknownTimeZoneError: 'Can not find timezone Northwest Time Border M�xico'"
"python: exited with code 1"
```
Not sure if this is an issue with the Windows installation reporting something strange, Python 3.7, or tzlocal not having this zone.

Looking at the IANA tzdata packages, this is indeed not a real Time Zone for Mexico, as IANA only identifies three zones:  
Baja California Norte (the Mexico/BajaNorte TZ)
Baja California Sur, Nayarit, Sinaloa and Sonora (the Mexico/BajaSur TZ)
The rest of the country (the Mexico/General TZ)

**Comment by regebro** [comment]
Correct, the timezone "Northwest Time Border Mexico" doesn't exist, and in fact Google can't find that phrase anywhere.
Try re-configuring your timezone in the control panel. I suspect they mean the "Tiempo del Noroeste" zone, which in zoneinfo terms is called "America/Tijuana", and in Windows *should* be called "Pacific Standard Time (Mexico)".

It's the same as US pacific time, so if you want you can try choosing that timezone instead, and it should work.

**Comment by Saijin-Naib** [comment]
Thank you!

It looks like they have their machine set for UTC -12.

Does it make sense to you that this was misreported?

![image001.png](https://user-images.githubusercontent.com/19295950/135730916-c44f49ee-cd9d-4a0f-ba99-a70d541e2793.png)

**Comment by regebro** [comment]
No, I don't think they have configured it like that, I think the control panel gets nonsense configuration and probably shows the first or the last entry in the list as a result. This increases the likelihood that setting it to the correct timezone will fix the problem.

**Comment by Saijin-Naib** [comment]
You were correct! Thanks so much.
