### ISSUE TITLE
get_localzone does not respect default GNU libc value for $TZ

### ISSUE THREAD

**Issue by robnagler** [regebro/tzlocal#125]
[21.5.6 Specifying the Time Zone with TZ](https://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html):
> If the TZ environment variable does not have a value, the operation chooses a time zone by default. In the GNU C Library, the default time zone is like the specification ‘TZ=:/etc/localtime’ (or ‘TZ=:/usr/local/etc/localtime’, depending on how the GNU C Library was configured; see Installation).

```sh
$ TZ=:/etc/localtime python -c 'import tzlocal; print(tzlocal.get_localzone())'
local
```

Why set $TZ at all? There's a [serious performance issue on Red Hat](https://blog.packagecloud.io/eng/2017/02/21/set-environment-variable-save-thousands-of-system-calls/) when TZ is not set.

**Comment by regebro** [comment]
I'll check it out. This format should be supported, but I do see I forgot to strip away the leading ":" in the `_tz_name_from_env()` function, maybe this confuses things.

**Comment by regebro** [comment]
4.2 should solve this
