### ISSUE TITLE
get_localzone returning 6:55 when used in Malaysia?

### ISSUE THREAD

**Issue by OptrixAU** [regebro/tzlocal#138]
While I don't have any issues with get_localzone in most other locations, I do have a site in Malaysia where it is returning a timezone offset of 6:55 (6 hours and 55 minutes) rather than 8 hours.

**Comment by regebro** [comment]
Strange. Could you install 4.4b1, and run the following code:
```
    import logging
    logging.basicConfig(level="DEBUG")
    import tzlocal
    tzlocal.get_localzone()
```

And send me the output?

**Comment by regebro** [comment]
Ah, no matter, 6:55 is the local solar time offset. That's what you get if you don't specify a datetime when you ask what the offset is. You need to specify a datetime, as the offset changes.
