### ISSUE TITLE
Logging issues since 5.0

### ISSUE THREAD

**Issue by Luc1412** [regebro/tzlocal#144]
Since the 5.0 release, it seems like there is a 2nd Logging Stream Handler in debug mode:

4.x:
![image](https://github.com/regebro/tzlocal/assets/24532065/73195baf-f04f-4da4-9526-dfc1590a3e94)

5.x
![image](https://github.com/regebro/tzlocal/assets/24532065/038cf6a0-64a8-45ce-ae03-57bea369d962)

Happens in my Debian Linux env (Docker) and local in staging on my Windows PC.

**Comment by regebro** [comment]
If I make a branch with a different usage of logging, can you install and test it?

**Comment by regebro** [comment]
I made a branch called improved-logging, as PR #151.
Also, here's a source package:

[tzlocal-5.1.dev0.tar.gz](https://github.com/regebro/tzlocal/files/11476791/tzlocal-5.1.dev0.tar.gz)

**Comment by Luc1412** [comment]
Tested it and it works fine as expected.

**Comment by regebro** [comment]
OK, cool!

**Comment by regebro** [comment]
Released that as 5.0.1
