### ISSUE TITLE
Downgrade multiple timezones to warning instead of error?

### ISSUE THREAD

**Issue by hmaarrfk** [regebro/tzlocal#165]
I'm not sure if this is an ubuntu 24.04 bug or a tzlocal bug, but here are the steps to recreate

```
$ echo "/etc/timezone $(cat /etc/timezone)" && ls -lah /etc/localtime
/etc/timezone America/New_York
lrwxrwxrwx 1 root root 36 Sep 20 11:11 /etc/localtime -> /usr/share/zoneinfo/America/New_York
```
Then go to the Ubuntu date and time settings and uncheck automatic timezone and change the timezone to be something else
```
$ echo "/etc/timezone $(cat /etc/timezone)" && ls -lah /etc/localtime
/etc/timezone America/New_York
lrwxrwxrwx 1 root root 39 Sep 20 08:12 /etc/localtime -> /usr/share/zoneinfo/America/Los_Angeles
```

Then you can't import your code anymore because the `/etc/localtime` and `/etc/timezone` conflict.

Would it be OK to let `/etc/localtime` take precedence and make the error below a warning instead of an error? Setting environment variables is somewhat annoying. 

Thank you for the consideration

https://github.com/user-attachments/assets/a233bc66-246a-4d04-8ddf-911f08c7a36a

```
  File "/home/mark/code.py", line 542, in add_timestamp
    local_timezone_name = tzlocal.get_localzone_name()
  File "/home/mark/miniforge3/envs/dev/lib/python3.10/site-packages/tzlocal/unix.py", line 209, in get_localzone_name
    _cache_tz_name = _get_localzone_name()
  File "/home/mark/miniforge3/envs/dev/lib/python3.10/site-packages/tzlocal/unix.py", line 159, in _get_localzone_name
    raise zoneinfo.ZoneInfoNotFoundError(message)
zoneinfo._common.ZoneInfoNotFoundError: 'Multiple conflicting time zone configurations found:\n/etc/timezone: America/New_York\n/etc/localtime is a symlink to: America/Los_Angeles\nFix the configuration, or set the time zone in a TZ environment variable.\n'

```

https://github.com/regebro/tzlocal/blob/52e53725f86fd74e551965de4e3a9f3aee826c8d/tzlocal/unix.py#L159

xref: https://github.com/regebro/tzlocal/issues/127

**Comment by regebro** [comment]
The purpose of tzlocal is to look at your computers configuration to find what timezone it is configured to. If it can't, it will fail. If the software you use don't actually need to know this, then it should wrap that call in a try/except and make it into a warning. But of tzlocal can't figure out the timezone, it will raise an error, because it's whole purpose of existence just failed. :-D

**Comment by hmaarrfk** [comment]
So could we work to improve the algorithm that it uses to figure out the timezone? 

I mean, the video i showed shows a typical user using the GUI to adjust their local timezone, then their python code failing.

If Ubuntu users are not part of your target audience that is fine, but I feel like my reproducing example was showed a real use case where the error provided didn't give me action item I could take....

**Comment by regebro** [comment]
That is then a bug in Ubuntu, yes. Using the GUI to adjust your timezone should not create an inconsistent configuration.

**Comment by hmaarrfk** [comment]
Ok. Then it might be a bug in Ubuntu 24.04. 

I’ll see how I can report it there. 

This symptom stopped me from changing my timezone when travelling …..

**Comment by hmaarrfk** [comment]
I did a fresh install on this computer. No upgrade

**Comment by liam-mipac** [comment]
I have the same issue on the Ubuntu 24.04 Github Actions Runner image.

I found this change in Systemd where it no longer updates /etc/timezone except on Debian.
https://github.com/systemd/systemd/blob/db11bab38ccf1ed257f310d29070843d4c58ea01/NEWS#L16139

So changing the timezone using timedatectl (which the GUI uses) doesn't update /etc/timezone.

**Comment by regebro** [comment]
5,3 will handle this better
