### ISSUE TITLE
CentOS get_timezone() 

### ISSUE THREAD

**Issue by c-x** [regebro/tzlocal#19]
CentOS 7 has removed the file `/etc/sysconfig/clock` for command like `timedatectl`.

The function `tzlocal.get_timezone()` which should return for example "Europe/Paris" is in that case returning "local", which is invalid.

```
CentOS 6
>>> tzlocal.get_localzone()
<DstTzInfo 'Europe/Paris' LMT+0:09:00 STD>

CentOS 7 (even though timedatectl is correctly set)
>>> tzlocal.get_localzone()
<DstTzInfo 'local' PMT+0:09:00 STD>
```

Workaround:
Create the file /etc/sysconfig/clock which contains the timezone.

Thanks

**Comment by regebro** [comment]
This has been fixed and will be included in the next release.
