### ISSUE TITLE
Failsafe for OS X (again)

### ISSUE THREAD

**Issue by mckabi** [regebro/tzlocal#20]
tzlocal and flask on virtualenv + Sublime Text 2 + OS X 10.10.5

```
sh: systemsetup: command not found
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
sh: systemsetup: command not found
```

"sh: systemsetup: command not found" from tzlocal.darwin:_get_localzone()

Solutions:

1. [Replace os.popen(command).read()... with subprocess.Popen(command, shell=True, stdout=PIPE, stderr=PIPE)](https://docs.python.org/2/library/subprocess.html#replacing-os-popen-os-popen2-os-popen3)
1. readlink /etc/localtime first

Replacing os.popen() is better than readlink first.

```python
from subprocess import Popen, PIPE

pipe = Popen("systemsetup -gettimezone", shell=True, stderr=PIPE, stdout=PIPE)
tzname = pipe.stdout.read().replace('Time Zone: ', '').strip()
```

Thanks

**Comment by regebro** [comment]
But if sh can't find system setup, will Popen find it?

**Comment by mckabi** [comment]
```python
>>> pipe = Popen("fakesystemsetup -gettimezone", shell=True, stderr=PIPE, stdout=PIPE)
>>> pipe.stdout.read()
''
>>> pipe.stderr.read()
'/bin/sh: fakesystemsetup: command not found\n'
>>>
```

then read link /etc/localtime

The point is,
- os.popen is deprecated since python 2.6
- os.popen can not handling stderr, subprocess.Popen can do it.

**Comment by regebro** [comment]
os.popen was deprecated in 2.6 for removal in Python 3, but it was never removed, so it's been "undeprecated". But you have a point about the error, that's better than a try/except.

I made a "darwin-20" branch with the fix, it would be nice if you could test it, I don't have a working OS X machine currently.

**Comment by regebro** [comment]
Merged
