### ISSUE TITLE
tzlocal on FreeBSD returns "local"

### ISSUE THREAD

**Issue by alcarithemad** [regebro/tzlocal#33]
In the same vein as issues #6 and #18.

Any thoughts on how to work around this?

For some additional fun, /etc/localtime isn't a symlink on FreeBSD.

```
$ pip list
pip (8.1.2)
pytz (2016.4)
setuptools (19.4)
tzlocal (1.2.2)
wheel (0.26.0)
$ python -c 'import tzlocal; print tzlocal.get_localzone()'
local
$ uname -a
FreeBSD host 10.3-RELEASE-p3 FreeBSD 10.3-RELEASE-p3 #0: Tue May 17 08:43:55 UTC 2016     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
$ ls -alh /etc/localtime
-r--r--r--  1 root  wheel   2.8K Jul  2  2015 /etc/localtime
$ file /etc/localtime
/etc/localtime: timezone data, version 2, 4 gmt time flags, 4 std time flags, no leap seconds, 185 transition times, 4 abbreviation chars
```

**Comment by alcarithemad** [comment]
I did a bit more research, and `/var/db/zoneinfo` should contain the name of the timezone currently in use.

There seems to be a bug in `tzsetup` where it won't update the file under certain conditions, but I'm filing a bug with FreeBSD about that right now.

**Comment by regebro** [comment]
Fix commited.
