### ISSUE TITLE
Wrong file check order for misconfigured Ubuntu 14.04 

### ISSUE THREAD

**Issue by ngo** [regebro/tzlocal#35]
We had an Ubuntu 14.04 setup where the /etc/localtime file was not in sync with /etc/timezone. System utilities (e.g. date) and many other programs (e.g. postgresql) use zone from /etc/localtime, but tzlocal first checks /etc/timezone. This results in the difference between the local zone as reported by tzlocal and as reported by date and other programs.

Though I understand the rationale behind using /etc/timezone first, maybe there is a way to handle even such msiconfigured systems properly? I would say that in case of misconfigurations the localtime should be preferred method to get the zone.

**Comment by regebro** [comment]
If we make extensive sanity checks, which will take time for very little use, then we could raise an error. That might also raise false positives.

**Comment by ngo** [comment]
Well, that is what I expected more or less, thanks for clarification.
