### ISSUE TITLE
Detection of the timezone name fails on Slackware

### ISSUE THREAD

**Issue by tbabej** [regebro/tzlocal#38]
As we found out with @treeman , tzlocal only manages to identify the timezone on Slackware as 'local', see:

    python3
    >>> import tzlocal
    >>> tzlocal.get_localzone()
    <DstTzInfo 'local' CET+1:00:00 STD>

https://github.com/tbabej/taskwiki/issues/116#issuecomment-272685858

**Comment by regebro** [comment]
We need the official way to get the time zone name on slackware, then I can implement a check for that.

**Comment by regebro** [comment]
According to the slackware docs, there is no way to fix this, short of comparing the binary timezone files, which is silly and slow so I refuse to implement that.

You can solve this by symlinking the timezone file instead of copying it when you configure the system.
