### ISSUE TITLE
get_localzone returns 'local' on alpine linux docker container (Python:alpine)

### ISSUE THREAD

**Issue by ibigpapa** [regebro/tzlocal#44]
When i run `tzlocal.get_localzone()` it returns `<StaticTzInfo 'local'>` 

Steps to recreate
1. Get into shell of container: `docker run --rm -it python:alpine /bin/sh`
2. Install tzlocal `pip install tzlocal`
3. Launch python `python`
4. Import and test
```python
>>> tzlocal.get_localzone()
<StaticTzInfo 'local'>
```

output of /etc/localtime
```bash
cat /etc/localtime 
TZif2UTCTZif2UTC
UTC0
```
`/usr/local/etc/localtime` does not exist.

**Comment by regebro** [comment]
This means none of the ways to figure out the time zone name worked. There may not be one on Alpine Linux, or it's sufficiently non-standard to not already be included.

Including a way would be possible if there is a reliable way to deduce the name in standard setups.

**Comment by ibigpapa** [comment]
Heres a way to determine the name.

```bash
cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.4.6
PRETTY_NAME="Alpine Linux v3.4"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
```

**Comment by regebro** [comment]
No, I mean the name of the time zone.

**Comment by ibigpapa** [comment]
You put me on the right path it appears that the Alpine docker container doesn't have TZ data in there. Following https://wiki.alpinelinux.org/wiki/Setting_the_timezone, makes it produce the proper TZ info when you call tzlocal.get_localzone()

**Comment by regebro** [comment]
Super!

**Comment by benjaoming** [comment]
This is reported to be a problem too in Windows' Ubuntu Bash thing: https://github.com/learningequality/kolibri/pull/2484

**Comment by regebro** [comment]
Your system isn't configured in such a way that it's possible to figure out the timezone name. The timezone object returned is therefore using the name "local" for the time zone. This is not a bug, but a feature.

If you want a time zone name, configure your system properly.

**Comment by benjaoming** [comment]
It's not my system, I'm reporting this on behalf of others having problems. The way I solved it wasn't to do much but raise `pytz.UnknownTimeZoneError`

**Comment by regebro** [comment]
Yeah, if you need a timezone name, and tzlocal doesn't give that, that's a reasonable way to handle it.
