### ISSUE TITLE
get_localzone() from tzlocal returns empty string

### ISSUE THREAD

**Issue by syracine** [regebro/tzlocal#52]
Hello,

I'm completely new in Python. I installed a Python backup software from pip on Debian 8 server running Python 2.7.9. When I type the following command in shell, I get the following exception:
`Python 2.7.9 (default, Jun 29 2016, 13:08:31)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from tzlocal import get_localzone
>>> tz=get_localzone()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tzlocal/unix.py", line 131, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/local/lib/python2.7/dist-packages/tzlocal/unix.py", line 70, in _get_localzone
    return pytz.timezone(etctz.replace(' ', '_'))
  File "/usr/local/lib/python2.7/dist-packages/pytz/__init__.py", line 191, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: ''`

My server is located in Quebec, Canada. I never used Python 2 or 3 before on this server. I installed this morning both Python 2 and 3 in parallel.  I installed pytz and tzlocal from pip. Do I miss something or is it a bug? I tried it with pytz 2017.3 and tzlocal 1.4. I upgraded to 1.5.1 and the bug appeared again.

Regards

Sylvain Racine

**Comment by regebro** [comment]
You probably have an `/etc/timezone` or a `/var/db/zoneinfo` file, but it is empty. It should contain the timezone name, like America/Toronto or something like that.

**Comment by syracine** [comment]
That is exactly what I need to know: how to set local timezone. Work fine now!

Thank!
