### ISSUE TITLE
tzlocal/test_data/symlink_localtime/etc/localtime isn't a symlink in the 1.5.1 release

### ISSUE THREAD

**Issue by EdwardBetts** [regebro/tzlocal#53]
The tests fail for the the 1.5.1 release on pypi. The test data is meant to include a symlink, it is a symlink in git and in the 1.4 pypi release, but it isn't for 1.5.1 on pypi.
```
======================================================================
FAIL: test_symlink_localtime (tzlocal.tests.TzLocalTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/edward/scratch/tzlocal2/tzlocal-1.5.1/tzlocal/tests.py", line 69, in test_symlink_localtime
    self.assertEqual(tz.zone, 'Africa/Harare')
AssertionError: 'local' != 'Africa/Harare'
- local
+ Africa/Harare
```
The first character in the tar file listing is 'l' for link in 1.4 and '-' for regular file in 1.5.1
```
$ tar tvzf tzlocal-1.4.tar.gz tzlocal-1.4/tzlocal/test_data/symlink_localtime/etc/localtime
lrwxrwxrwx lregebro/lregebro 0 2017-04-18 17:51 tzlocal-1.4/tzlocal/test_data/symlink_localtime/etc/localtime -> ../usr/share/zoneinfo/Africa/Harare
$ tar tvzf tzlocal-1.5.1.tar.gz tzlocal-1.5.1/tzlocal/test_data/symlink_localtime/etc/localtime
-rw-rw-r-- lregebro/lregebro 157 2017-12-01 09:37 tzlocal-1.5.1/tzlocal/test_data/symlink_localtime/etc/localtime
$
```

**Comment by regebro** [comment]
Huh, interesting. It is a symlink in git, so there must be some change in how the tarring is done. I'll take a look at it, but the end result may be that I move the tests outside of the package so that they aren't included in the distribution at all. I've started doing that with my packages now.

**Comment by EdwardBetts** [comment]
Thanks @regebro. I packaged tzlocal for Debian using the pypi release. The Debian package build runs the testsuite, this is useful to catch any errors in the packaging. I'd encourage you to keep the tests in the pypi release. If you do decided to remove the testsuite from the version on pypi then I can probably switch to using the github release.

**Comment by regebro** [comment]
I can't find a solution for this, sorry. I moved the tests out of the package, so the github release is probably the right way to go.

**Comment by regebro** [comment]
Can't do much else about this, so closing.
