### ISSUE TITLE
IOError: [Errno 21] Is a directory: '/etc/sysconfig/clock'

### ISSUE THREAD

**Issue by jason-huling** [regebro/tzlocal#58]
Hey @regebro,

We are using [exchangelib](https://github.com/ecederstrand/exchangelib) which internally calls the tzlocal library as referenced here:
[tz = tzlocal.get_localzone()](https://github.com/ecederstrand/exchangelib/blob/af6b3e18dfa2e68b0231d1ab997ca73e2ea7237f/exchangelib/ewsdatetime.py#L221)

We are getting the following error sporadically 
```
Traceback (most recent call last):
    File "<...>.py", line 69, in <module>
    access_type = exchangelib.DELEGATE)
    File "<venv>/lib/python2.7/site-packages/exchangelib/account.py", line 80, in __init__
    self.default_timezone = default_timezone or EWSTimeZone.localzone()
    File "<venv>/lib/python2.7/site-packages/exchangelib/ewsdatetime.py", line 208, in localzone
    tz = tzlocal.get_localzone()
    File "<venv>/lib/python2.7/site-packages/tzlocal/unix.py", line 131, in get_localzone
    _cache_tz = _get_localzone()
    File "<venv>/lib/python2.7/site-packages/tzlocal/unix.py", line 85, in _get_localzone
    with open(tzpath, 'rt') as tzfile:
    IOError: [Errno 21] Is a directory: '/etc/sysconfig/clock'
```
Which traces back to the following code:
https://github.com/regebro/tzlocal/blob/a117f96f975febd4d9d7b51c71bda65ab4424303/tzlocal/unix.py#L83-L86

It seems as though for some reason there might be a directory on the server we are running this on at "/etc/sysconfig/clock", and therefore the `os.path.exists` check returns true, but then the code tries to read it as a file and fails. 

Since the code is expecting this to be a file, would it be more appropriate to do an explicit `os.path.isfile` check?

Or even better, just wrapping the code that is opening the file in a `try` block, which seems to be preferred and resilient to possible race conditions based on [this StackOverflow answer](https://stackoverflow.com/a/82852/3723796). For example:
```
try:
    with open(tzpath, 'rt') as tzfile:
        data = tzfile.readlines()
except IOError:
    continue
```

Are you open to either of these suggestions?

**Comment by regebro** [comment]
Done!
