### ISSUE TITLE
get_localzone issue with amazonlinux distribution

### ISSUE THREAD

**Issue by qli-aa** [regebro/tzlocal#60]
amazonlinux had /etc/localtime file, but it was not a symlink, so when I call get_localzone, it always return **<StaticTzInfo 'local'>** instead of right timezone info, like **<StaticTzInfo 'Etc/UTC'>**

**Comment by regebro** [comment]
That's a feature, not a bug. If tzlocal can't figure out the name of the timezone configured, it will return your  timezone configuration, but without the name.

You can put in the timezone name (in your case UTC) in /etc/timezone, then tzinfo will find this and use it.
