### ISSUE TITLE
Build & upload wheels to PyPI?

### ISSUE THREAD

**Issue by thanatos** [regebro/tzlocal#63]
Would it be possible for this project to upload wheels to PyPI?

Since this is a pure Python project, this should be relatively simple, as there is no compile step.

Also, since this project is 2/3 compatible, and pure Python, I think it qualifies as a "universal" wheel, so you might want to put

```
[wheel]
universal = 1
```

in `setup.cfg` prior to building the wheels. (This will build a single `.whl` wheel file for both Python 2 & 3, so the installed code must be good for both. Typically, pure-python projects are, and looking over `tzlocal`, I don't see any reason why this wouldn't work.)

**Comment by regebro** [comment]
Thanks for kicking me to do this. Future releases (including the new 2.0.0b1) will have wheels.

**Comment by thanatos** [comment]
Thank you!
