### ISSUE TITLE
Empty ubuntu docker container (UTC) failure to run `get_localzone`

### ISSUE THREAD

**Issue by asottile** [regebro/tzlocal#70]
I'm not sure what to expect, the readme leads me to believe 

> Please note that if you getting a time zone called local, this is not a bug, it's actually the main feature of tzlocal, that even if your system does NOT have a configuration file with the zoneinfo name of your time zone, it will still work.

that I shouldn't get a crash.

Here's a reproduction with docker:

```bash
docker run --rm -ti ubuntu:bionic bash -euxc 'apt-get update -qqq && DEBIAN_FRONTEND=noninteractive apt-get install -qqq -y --no-install-recommends python3-pip python3-setuptools && pip3 install tzlocal && python3 -c "import tzlocal; tzlocal.get_localzone()"'
```

```
...
Installing collected packages: pytz, tzlocal
  Running setup.py install for tzlocal ... done
Successfully installed pytz-2018.7 tzlocal-1.5.1
+ python3 -c 'import tzlocal; tzlocal.get_localzone()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/tzlocal/unix.py", line 131, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/local/lib/python3.6/dist-packages/tzlocal/unix.py", line 125, in _get_localzone
    raise pytz.UnknownTimeZoneError('Can not find any timezone configuration')
pytz.exceptions.UnknownTimeZoneError: 'Can not find any timezone configuration'
```

The timezone in the container is UTC:

```
$ docker run --rm -ti ubuntu:bionic date +%Z
UTC
```

**Comment by thanatos** [comment]
I can confirm this. `tzlocal.get_localzone()` raises an exception in a `ubuntu:bionic` container w/ nothing added to it except Python 3 & `tzlocal`.

The difference between the `bionic` and `xenial` (the preceding Ubuntu LTS) containers seems to be that `bionic` lacks both `/etc/localtime` and `/etc/timezone`. Without those, `tzlocal` raises.

The readme also states,

> Any unix-like system with a /etc/localtime or /usr/local/etc/localtime

If I copy the `/etc/localtime` from Xenial into the Bionic container, `tzlocal` _still_ raises. On Xenial, it's a symlink:
```
lrwxrwxrwx 1 root root      27 Jan 23  2018 localtime -> /usr/share/zoneinfo/Etc/UTC
```
Now, it's also a _broken_ symlink in Xenial. It's adding `/etc/timezone` that actually works for me in Bionic. (Which is a text file whose content is a zone name followed by a newline.) So I suspect on both Xenial, `tzlocal` ignores the broken symlink, and gets the information from `/etc/timezone`.


I agree w/ @asottile: the README suggests this should work. Additionally, glibc/C programs can get the timezone just fine; glibc seems to default to UTC in the presence of no config files and no environment variables. I think `tzlocal` should mirror `glibc`'s behavior here.

**Comment by asottile** [comment]
Empty `ubuntu:bionic` doesn't ship with the `tzdata` package by default (which is where those files come from), whereas `ubuntu:xenial` does

**Comment by regebro** [comment]
So, in fact, an empty ubuntu:bionic doesn't have any timezone configuration. Crazy....

Anyway, I actually use docker in my new job, I'll try to get time to verify this. If there really is no config, then the only way out of this is to have a default when no config is found, and I really don't want to do that.

**Comment by tommycahir** [comment]
Try edit the container and then create a environment variable

name = TZ
value = your time zone eg America/Toronto

**Comment by regebro** [comment]
Would be cool if someone that had this issue in real life can test this out from master before I release it.

**Comment by asottile** [comment]
Using a tweaked reproduction of above:

```console
$ docker run --rm -ti ubuntu:bionic bash -euxc 'apt-get update -qqq && DEBIAN_FRONTEND=noninteractive apt-get install -qqq -y --no-install-recommends python3-pip python3-setuptools git ca-certificates && pip3 install git+https://github.com/regebro/tzlocal && python3 -c "import tzlocal; tzlocal.get_localzone()"'

...

+ pip3 install git+https://github.com/regebro/tzlocal
Collecting git+https://github.com/regebro/tzlocal
  Cloning https://github.com/regebro/tzlocal to /tmp/pip-ja8wz1tp-build
Collecting pytz (from tzlocal==2.0.0.dev0)
  Downloading https://files.pythonhosted.org/packages/3d/73/fe30c2daaaa0713420d0382b16fbb761409f532c56bdcc514bf7b6262bb6/pytz-2019.1-py2.py3-none-any.whl (510kB)
    100% |################################| 512kB 1.7MB/s 
Installing collected packages: pytz, tzlocal
  Running setup.py install for tzlocal ... done
Successfully installed pytz-2019.1 tzlocal-2.0.0.dev0
+ python3 -c 'import tzlocal; tzlocal.get_localzone()'
/usr/local/lib/python3.6/dist-packages/tzlocal/unix.py:158: UserWarning: Can not find any timezone configuration, defaulting to UTC.
  warnings.warn('Can not find any timezone configuration, defaulting to UTC.')
```

**Comment by regebro** [comment]
OK, that looks good.
