### ISSUE TITLE
Release with python 3.8 support

### ISSUE THREAD

**Issue by imomaliev** [regebro/tzlocal#83]
Hi, I see there is an issue with python 3.8, but it was already fixed in master can it be released?

**Comment by regebro** [comment]
It's just a warning, it still works under Python 3.8. But sure, I'll release a new version soon.

**Comment by joekohlsdorf** [comment]
@regebro Any update on that release? :-)

**Comment by regebro** [comment]
A new beta is released (it's a beta because I changed the behaviour in one spot) that officially supports Python 3.8, and I got no warnings with Python 3.8.1.

**Comment by agronholm** [comment]
How long are you planning to keep the beta going before releasing v2.1?

**Comment by regebro** [comment]
Planning is for people with organizational skills.
