### ISSUE TITLE
AzurePipelines not working for linux or windows

### ISSUE THREAD

**Issue by timkpaine** [regebro/tzlocal#87]
Running on Azure pipelines, I get the following error running `get_localzone`:

```
tz = <StaticTzInfo 'Etc/UTC'>

    def get_tz_offset(tz):
        """Get timezone's offset using built-in function datetime.utcoffset()."""
>       return int(datetime.datetime.now(tz).utcoffset().total_seconds())
E       AttributeError: 'NoneType' object has no attribute 'total_seconds'
```

**Comment by regebro** [comment]
None? Weird...

**Comment by timkpaine** [comment]
let me know whatever other info might be helpful, here are the logs (should be public):
https://dev.azure.com/tpaine154/pyEX/_build/results?buildId=447&view=logs&j=936136b6-c495-56a6-9e3e-988b38df8fb3&t=a5d5bb20-0db0-56c2-52b2-9c5d6dccb8d3&l=468

**Comment by timkpaine** [comment]
interestingly it fails with the same error on windows and linux but not mac

**Comment by regebro** [comment]
I think this is a bug with Azure pipelines. Does it still happen?

**Comment by timkpaine** [comment]
@regebro ive been moving over to github actions, feel free to close and I'll ping to reopen if I see it again
