### ISSUE TITLE
cannot import name 'get_localzone' from 'tzlocal' (unknown location)

### ISSUE THREAD

**Issue by andocromn** [regebro/tzlocal#88]
I am receiving an error "ImportError: cannot import name 'get_localzone' from 'tzlocal' (unknown location)" in python3.7.3 on the line "from tzlocal import get_localzone"

I am on debian 10.3, I have run dpkg-reconfigure tzdata to reconfigure the timezone, reboot, still occurs.  I'm unsure of how tzlocal determines the local timezone?  Any help would be appreciated

**Comment by regebro** [comment]
Either the package isn't correctly installed, or you have some sort of name clash. Is there perhaps another file called tzlocal.py somewhere?

> I'm unsure of how tzlocal determines the local timezone?

That depends, but as you can't import it, it's not relevant for this question.

**Comment by andocromn** [comment]
uninstall reinstall worked thanks
