### ISSUE TITLE
Please add python_requires

### ISSUE THREAD

**Issue by pganssle** [regebro/tzlocal#93]
It seems that in the next release you intend to drop support for Python 2, but there is no [`python_requires`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires) in your `setup.py`.

You should add `python_requires=">=3.6"` to the `setup()` call, or it will cause a lot of unnecessary headaches, and there's a good chance you'll have to [yank](https://www.python.org/dev/peps/pep-0592/) the first release without a `python_requires`.

**Comment by agronholm** [comment]
Covered in this PR: https://github.com/regebro/tzlocal/pull/94
